### PR TITLE
PointerType for ink editor

### PR DESCRIPTION
**Pull request by legraina**
Add PointerType to ensure that only the right pointer type can start a drawing session

### CODE REVIEW

**Comment by legraina** [comment]
It's linked to ngx-extended issue  Writing and scrolling at the same time for touch (2597)

**Comment by legraina** [comment]
Also, I didn't tested it as I do not know how to put it in the whole pipeline.

**Comment by stephanrauh** [comment]
You can test it by running `npm install` and `gulp server` in the pdf.js folder. This starts a web server on port 8888. It starts with a folder view, and you have to navigate this view to the example pdf file to open it.

Trying to get it up and running in ngx-extended-pdf-viewer doesn't work right now. For some reason unknown, the ink editor doesn't paint anything in the bleeding-edge branch. I suspect a CSS problem, but I'm not sure yet.

**Comment by legraina** [comment]
I've tested on my computer, and it seems to work. However, I have not been able to connect to my computer from my tablet to test it, but I'm pretty sure it should be good. 
Finally, I have also added for highlight as it was straightforward. 
BTW, I had to run ``npm install canvas-size`` as it was missing.
See PR #9 for both.

**Pull request merged**
